name: Search CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  precommit_check:
    name: Precommit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Search
        uses: actions/checkout@v2
      - name: Setup Java 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run Precommit Checks
        run: ./gradlew precommit --parallel
